services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: korp-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Korp@123456"
    ports:
      - "1433:1433"
    volumes:
      - dados_sqlserver:/var/opt/mssql
    restart: unless-stopped

volumes:
  dados_sqlserver: